pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://files.minecraftforge.net/maven/' }
        maven {
            name = "CurseMaven"
            url = uri("https://cursemaven.com")
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'sky_village_islands'

include 'common'
include 'fabric'
include 'forge'
