modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sky_village_islands"
version = "${version}"
displayName = "Sky Village Islands"
authors = "Slickson"
description = '''
A new take on sky villages - Village generation in the sky with houses and structures dynamically generated on islands connected by bridges.
'''
#logoFile = ""

[[dependencies.sky_village_islands]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sky_village_islands]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sky_village_islands]]
modId= "lithostitched"
mandatory=true
versionRange="[1.5,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "sky_village_islands.mixins.json"
